
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
body{
    background:#F8F9F9;
    margin:5px;
}

input, select {
    width: 100%;
    padding: 3px 3px;
    margin: 5px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

p {
    margin: 5px 0;
    color: #E74C3C;
}

</style>


<table width="100%">
    <tr>
        <td colspan="3">
            <center>  <h2> PHP-CI-MODCON (Version 3.0) </h2>  </center>

            <p> Whoohoo!! The PHP-CI-MODCON will help you to boost your development speed as it will help you to generate 
            controllers and models in just few seconds with all the CRUD operation methods readymate inside it which is 
            directly available to use with all the neccessory parameter inside it. All you need to do is copy the models 
            and controllers generated by PHP-CI-MODCON into your CodeIgnitor project and pass the parameter by calling the
            methods to perform CRUD operation and many more. Easy right !! 😃 - <a style="color:blue; " href="https://github.com/zaidpathanGit" target="_blank"> zaidpathanGit </a> 
            </p> <br>
        </td>
    </tr>
</table>


<div class="w3-bar w3-black">
    <button class="w3-bar-item w3-button" onclick="openCity(&#39;Tab1&#39;)">Database Configuration</button>
    <button class="w3-bar-item w3-button" onclick="openCity(&#39;Tab2&#39;)">Database Info</button>
    <button class="w3-bar-item w3-button" onclick="openCity(&#39;Tab3&#39;)">Generate Controller[s]</button>
    <button class="w3-bar-item w3-button" onclick="openCity(&#39;Tab4&#39;)">Generate Model[s]</button>
</div>


<!-- Tabs starts from here -->
<div id="Tab1" class="w3-container city" style="display: block;">
    <table>
        <tr>
            <!-- Code to design form for database configuration -->
            <form method="post">
            <td> <input type="text" name="hostName" placeholder="Enter host name" required> </td>

            <td> <input type="text" name="username" placeholder="Enter username"> </td>

            <td> <input type="password" name="password" placeholder="Enter password"> </td>
            
            <td> <input type="submit" name="configureDatabase" value="Configure connection"> </td>
            </form>
                    
        </tr>
    </table>
</div>


<div id="Tab2" class="w3-container city" style="display: none;">
    <table>
        <tr>
            <td>
                <!-- Code to design form for database name input -->
                <form method="post">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="text" name="databaseName" placeholder="Enter database name" required="">
                    <input type="submit" name="showDatabaseTables" value="Show database tables">
                </form>
            </td>

            <td>
                <!-- Code to design form for display fields of particular table -->
                <form method="post">
                    <input type="number" name="tableIndex" placeholder="Enter table index" min="1" required="">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="hidden" name="databaseName" value="<?php if(isset($_POST['databaseName'])){ echo $_POST['databaseName']; } ?>">
                    <input type="submit" name="showDatabaseTableFields" value="Show database table fields">
                </form>
            </td>
        </tr>
    </table>
</div>


<div id="Tab3" class="w3-container city" style="display: none;">
    <table>
        <tr>
            <td>
                <!-- Code to design form for generate single controller -->
                <form method="post">
                    <input type="number" name="tableIndex" placeholder="Enter table index" min="1" required="">
                    <input type="text" name="path" placeholder="C://wamp//yourProject// or leave blank for default location">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="hidden" name="databaseName" value="<?php if(isset($_POST['databaseName'])){ echo $_POST['databaseName']; } ?>">
                    <input type="submit" name="generateSingleController" value="Generate single controller">
                </form>
            </td>

            <td>
                <!-- Code to design form for generate controllers for multiple tables -->
                <form method="post">
                    <input type="number" name="tableIndex" placeholder="Enter table index" min="1" disabled="">
                    <input type="text" name="path" placeholder="C://wamp//yourProject// or leave blank for default location">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="hidden" name="databaseName" value="<?php if(isset($_POST['databaseName'])){ echo $_POST['databaseName']; } ?>">
                    <input type="submit" name="generateControllers" value="Generate controllers">
                </form>
            </td>
        </tr>
    </table>
</div>


<div id="Tab4" class="w3-container city" style="display: none;">
    <table>
        <tbody><tr>
            <td>
                <!-- Code to design form for generate single model -->
                <form method="post">
                    <input type="number" name="tableIndex" placeholder="Enter table index" min="1" required="">
                    <input type="text" name="path" placeholder="C://wamp//yourProject// or leave blank for default location">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="hidden" name="databaseName" value="<?php if(isset($_POST['databaseName'])){ echo $_POST['databaseName']; } ?>">
                    <input type="submit" name="generateSingleModel" value="Generate single model">
                </form>
            </td>

            <td>
                <!-- Code to design form for generate models for multiple tables -->
                <form method="post">
                    <input type="number" name="tableIndex" placeholder="Enter table index" min="1" disabled="">
                    <input type="text" name="path" placeholder="C://wamp//yourProject// or leave blank for default location">
                    <input type="hidden" name="hostName" value="<?php if(isset($_POST['hostName'])){ echo $_POST['hostName']; } ?>">
                    <input type="hidden" name="username" value="<?php if(isset($_POST['username'])){ echo $_POST['username']; } ?>">
                    <input type="hidden" name="password" value="<?php if(isset($_POST['password'])){ echo $_POST['password']; } ?>">
                    <input type="hidden" name="databaseName" value="<?php if(isset($_POST['databaseName'])){ echo $_POST['databaseName']; } ?>">
                    <input type="submit" name="generateModels" value="Generate models">
                </form>
            </td>
        </tr>
    </tbody></table>      
</div>

<!-- Tabs ends from here -->


<!-- Code to display particular tab when user clicks on button -->
<script>
    function openCity(cityName) {
    var i;
    var x = document.getElementsByClassName("city");
    for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";  
    }
    document.getElementById(cityName).style.display = "block";  
    }
</script>


<?php
require_once("databaseConfigure.php");
require_once("modelGenerator.php");
require_once("controllerGenerator.php");


//Variable to store table list 
$tableList = null;


//Code to be executed when showDatabaseTables button is clicked
if(isset($_POST['showDatabaseTables']) || isset($_POST['showDatabaseTableFields']) || 
    isset($_POST['generateSingleController']) || isset($_POST['generateControllers']) || 
    isset($_POST['generateSingleModel']) || isset($_POST['generateModels']) || 
    isset($_POST['configureDatabase']))
{
    
    /**
     * Creating and initializing object of databaseConfigure class.
     */
    $obj = new databaseConfigure($_POST['hostName'], $_POST['username'], $_POST['password'], $_POST['databaseName']);
    
    /**
     * Code to get all tables list from the specified database into the parameter.
     */
    $databaseList = $obj->getAllDatabases();

    echo "<hr> The following tables are available in your database. <hr>";

    var_dump($databaseList);

}


//Code to be executed when showDatabaseTables button is clicked
if(isset($_POST['showDatabaseTables']) || isset($_POST['showDatabaseTableFields']) ||
    isset($_POST['generateSingleController']) || isset($_POST['generateControllers']) || 
    isset($_POST['generateSingleModel']) || isset($_POST['generateModels']))
{
    /**
     * Code to get all databases list from the specified connection into the parameter.
     */
    $tableList = $obj->getAllTables();

    echo "<hr> The following tables are available in your database. <hr>";

    var_dump($tableList);
}


//Code to be executed when showDatabaseTableFields button is clicked
if(isset($_POST['showDatabaseTableFields']))
{
    /**
     * Code to get fields list from the specified table into the parameter.
     */
    $fieldList = $obj->getTableFields($tableList[$_POST['tableIndex']]);

    echo "<hr> The following fields are available in your table. <hr>";

    var_dump($fieldList);
}


//Code to be executed when generateSingleController button is clicked
if(isset($_POST['generateSingleController']))
{
    /**
     * Code to set value for path variable. Change value only if path is not null from $_POST['path']
     */
    $path = null;
    if(isset($_POST['path']) != null)
    {
        $path = $_POST['path'];
    }

    /**
     * Make an object of controllerGenerator class to access its methods.
     */
    $obj1 = new ControllerGenerator();
    
    /**
     * Call the methods to generate single model or for all the tables available inside your database.
     */
    $obj1->generateSingleController($tableList[$_POST['tableIndex']], $path); //pass null parameter for default location.
}


//Code to be executed when generateControllers button is clicked
if(isset($_POST['generateControllers']))
{
    /**
     * Code to set value for path variable. Change value only if path is not null from $_POST['path']
     */
    $path = null;
    if(isset($_POST['path']) != null)
    {
        $path = $_POST['path'];
    }

    /**
     * Make an object of controllerGenerator class to access its methods.
     */
    $obj1 = new ControllerGenerator();
    
    /**
     * Call the methods to generate single model or for all the tables available inside your database.
     */
    $obj1->generateController($tableList, $path); //pass null parameter for default location.
}


//Code to be executed when generateSingleModel button is clicked
if(isset($_POST['generateSingleModel']))
{
    /**
     * Code to set value for path variable. Change value only if path is not null from $_POST['path']
     */
    $path = null;
    if(isset($_POST['path']) != null)
    {
        $path = $_POST['path'];
    }

    /**
     * Make an object of ModelGenerator class to access its methods.
     */
    $obj2 = new ModelGenerator();

    /**
     * Call the methods to generate single controller. or for all the tables available inside your database.
     */
    $obj2->generateSingleModel($tableList[$_POST['tableIndex']], $path); //pass null parameter for default location.
}


//Code to be executed when generateModels button is clicked
if(isset($_POST['generateModels']))
{
    /**
     * Code to set value for path variable. Change value only if path is not null from $_POST['path']
     */
    $path = null;
    if(isset($_POST['path']) != null)
    {
        $path = $_POST['path'];
    }

    /**
     * Make an object of ModelGenerator class to access its methods.
     */
    $obj2 = new ModelGenerator();

    /**
     * Call the methods to generate single controller. or for all the tables available inside your database.
     */
    $obj2->generateModel($tableList, $path); //pass null parameter for default location
}


?>